### ISSUE TITLE
Weird background scrolling

### ISSUE THREAD

**Issue by de-katze** [SomeAspy/aspy.dev#40]
Safari on iOS, contains a weird scrolling effect on the background 

Side note, footer is cutoff 

https://github.com/SomeAspy/aspy.dev/assets/143244075/b02650be-ace0-4531-876d-a7a6ddb22203

**Comment by SomeAspy** [comment]
This is explicitly an issue on mobile. Mobile devices disable the `background-attachment:fixed` CSS option[for performance](https://stackoverflow.com/questions/56208961/fixed-background-on-scroll-on-mobile-devices). I don't currently have a fix for this.
